version: '3.7'
services:
   postgres:
       image: debezium/postgres:15-alpine
       container_name: postgres
       hostname: postgres
       restart: always
       ports:
           - '5443:5432'
       environment:
           POSTGRES_PASSWORD: P123!
           POSTGRES_USER: postgres
           POSTGRES_DB: data-liberation
       volumes:
           - './docker/postgres-data:/var/lib/postgresql/data'
       networks:
           - log-based-network


   kafka:
       image: bitnami/kafka:3.7.0
       container_name: kafka
       hostname: kafka
       restart: always
       ports:
           - '9092:9092'
       environment:
           KAFKA_CFG_NODE_ID: 1
           KAFKA_KRAFT_CLUSTER_ID: q0k00yjQRaqWmAAAZv955w # base64 UUID
           KAFKA_CFG_PROCESS_ROLES: controller,broker
           KAFKA_CFG_LISTENERS: INTERNAL://kafka:29092,CONTROLLER://kafka:29093,EXTERNAL://0.0.0.0:9092
           KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
           KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
           KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
           KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
           KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
       networks:
           - log-based-network


   debezium:
       image: debezium/connect:2.3
       container_name: debezium-connect
       hostname: debezium-connect
       restart: always
       ports:
           - '8083:8083'
       environment:
           BOOTSTRAP_SERVERS: kafka:29092
           GROUP_ID: "debezium_group"
           CONFIG_STORAGE_TOPIC: debezium_connect_configs
           OFFSET_STORAGE_TOPIC: debezium_connect_offsets
           STATUS_STORAGE_TOPIC: debezium_connect_statuses
           ENABLE_DEBEZIUM_SCRIPTING: 'true'
       links:
           - kafka
           - postgres
       networks:
           - log-based-network

networks:
   log-based-network:
       name: log-based-network
       driver: bridge
       external: false

